spring.application.name=SpringToDo

spring.datasource.url=jdbc:postgresql://localhost:5432/tododb
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

flyway.enabled=true
flyway.base-line-on-migrate=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

management.endpoints.web.exposure.include= health,metrics,info

server.port=8080
